version: 2

models:

  - name: int_sales_margin
    description: Add purchase cost and margin
    columns:
      - name: date_date
      - name: products_id
        description: primary key with orders_id
        tests:
          - relationships:
              field: products_id
              to: ref('stg_raw__product')
      - name: orders_id
        description: primary key with products_id
        tests:
          - relationships:
              field: orders_id
              to: ref('stg_raw__sales')
      - name: purchase_cost
      - name: margin

  - name: int_orders_margin
    description: revenue, quantity, purchase_cost and margin grouped by order
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique

  - name: int_orders_operational
    description: Add operational margin
    columns:
      - name: date_date
      - name: orders_id
        description: primary key
        tests:
          - unique
      - name: operational_margin
        description: margin + shipping_fee - logcost - ship_cost
  - name: finance_days
    description: nb_transactions/revenue/average_basket/margin/operational_margin/purchase_cost/shipping_fee/log_cost/quantity grouped by days
    columns:
      - name: date_date
        description: primary key
        tests:
          - unique
  
  - name: int_campaigns.sql
    description: all advertisers join
    columns:
      - name: date_date
        description: primary key with campaign_key
      - name: paid_source
        description: name of advertiser
      - name: campaign_key
        description: primary key with date_date
      - name: camPGN_name
        description: campaign name
      - name: ads_cost
        description: advertisement cost
      - name: impression
        description: number of mail
      - name: click
        description: number of click

  - name: int_campaigns_day
    description: aggregated version of int_campaigns model for each day
    columns:
      - name: date_date
        description: primary key
        tests:
          - unique
      - name: ads_cost
        description: Sum of cost by day
      - name: ads_impression
        description: Sum of impression by day
      - name: ads_click
        description: Sum of click by day

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: products & price
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: price
      - name: sales
        identifier: raw_gz_sales
        description: date of sales & revenue
        freshness:
          warn_after: { count: 90, period: day }
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: primary key with products_id
          - name: pdt_id
            description: primary key with orders_id
          - name: revenue
            description: turnover by sales of products
          - name: quantity
            description: number of product sold
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: infos for shipping by orders
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: "client fee"
          - name: logCost
            description: logistic cost
          - name: ship_cost
            description: cost of shipping
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords campaign
        columns:
          - name: date_date
            description: primary key with campaign_key
          - name: paid_source
            description: name of advertiser
          - name: campaign_key
            description: primary key with date_date
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: advertisement cost
          - name: impression
            description: number of mail
          - name: click
            description: number of click
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: bing campaign
        columns:
          - name: date_date
            description: primary key with campaign_key
          - name: paid_source
            description: name of advertiser
          - name: campaign_key
            description: primary key with date_date
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: advertisement cost
          - name: impression
            description: number of mail
          - name: click
            description: number of click
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo campaign
        columns:
          - name: date_date
            description: primary key with campaign_key
          - name: paid_source
            description: name of advertiser
          - name: campaign_key
            description: primary key with date_date
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: advertisement cost
          - name: impression
            description: number of mail
          - name: click
            description: number of click
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook campaign
        columns:
          - name: date_date
            description: primary key with campaign_key
          - name: paid_source
            description: name of advertiser
          - name: campaign_key
            description: primary key with date_date
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: advertisement cost
          - name: impression
            description: number of mail
          - name: click
            description: number of click
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
